### ISSUE TITLE
install does not include required packages

### ISSUE THREAD

**Issue by brentp** [gogetdata/ggd-cli#16]
I see:
```
ggd --version
Traceback (most recent call last):
  File "/home/brentp/miniconda3/bin/ggd", line 7, in <module>
    from ggd.__main__ import main
  File "/home/brentp/miniconda3/lib/python3.7/site-packages/ggd/__main__.py", line 6, in <module>
    from . list_files import add_list_files
  File "/home/brentp/miniconda3/lib/python3.7/site-packages/ggd/list_files.py", line 14, in <module>
    from .search import load_json_from_url, search_packages
  File "/home/brentp/miniconda3/lib/python3.7/site-packages/ggd/search.py", line 11, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'
```
after doing the install as suggested in the readme.

**Comment by mikecormier** [comment]
This should be fixed. This is confirmed by the CI system for unit testing that is built every night.
